### ISSUE TITLE
Final CheckList

### ISSUE THREAD

**Issue by AlexisSB** [AlexisSB/242A1HashChaining#11]
- Use valgrind to check all files for memory leaks.
- Check for anylines longer than 80 characters.
 - Check all functions are commented appropriately.
- Check style, indentation, braces etc make sure its all clean and consistent.
- Double check the assignment document.

**Comment by rycoll** [comment]
Did we ever decide if comments should go in the .c or .h files? The assignment spec doesn't seem to say either way.

**Comment by rycoll** [comment]
"You can choose to put most of your comments in either the .c or
the .h files (but all files should contain some comments)."

**Comment by AlexisSB** [comment]
Spell check comments as well
