### ISSUE TITLE
Implement container.c and container.h

### ISSUE THREAD

**Issue by AlexisSB** [AlexisSB/242A1HashChaining#6]

**Comment by AlexisSB** [comment]
Container is a wrapper for flexarray or red-black tree.
Contains container struct.

Each function in container.c should call the appropriate function in either flexarray or red-black tree
e.g for adding a item to the container.
void container_add(container c, char *word) {
    if (c->type == RED_BLACK_TREE) {
        c->contents = rbt_insert(c->contents, word);
    } else {
        flexarray_append(c->contents, word);
    }
}

**Comment by rycoll** [comment]
This is basically done, I think?
container_add will need to be modified slightly once flexarray works with strings.

**Comment by AlexisSB** [comment]
Yeap. Container.c made with the rbt methods connect to rbt.c. Only flexarray to sort and moving this to a different issue.
